### ISSUE TITLE
웹 스터디 사이트 추천

### ISSUE THREAD

**Issue by CreatiCoding** [CreatiCoding/CoUPWA#26]
Html 기본 강의
https://opentutorials.org/course/2039

Html 예제 사이트
https://www.w3schools.com/tags/default.asp

**Comment by Rohheejung** [comment]
HTML, CSS 공부중

**Comment by kishu** [comment]
기초 위주로 쉽게 학습할 수 있음
https://www.codeschool.com/

좀 더 체계적이고 디테일한 학습
https://www.pluralsight.com/

코드 위지 깊은 학습
http://egghead.io/

다양하고 전문적인 학습
https://www.udemy.com/

**Comment by tentasys** [comment]
제가 2017년도에 진행했던 웹 세미나 관련 자료입니다.
완전 초보 기준으로 설명해 놓긴 했지만 도움이 될까 하여 링크 올려드립니다.
https://drive.google.com/file/d/1GBRx3jA5NpfnGXYLfvDo026p1M1KY21P/view?usp=sharing
https://drive.google.com/file/d/1tSeucdFyRo8FcMCsvjcaOM2B8pZlS0C2/view?usp=sharing
https://drive.google.com/file/d/1hHEH1Xp1EJOeil1btQ9SFZN0U-OjvXjV/view?usp=sharing
https://drive.google.com/file/d/1Xtk8Z-Iaaqvhz7xUtZ-KpP67rUmzM9X-/view?usp=sharing
https://drive.google.com/file/d/1iDmavtC5MhexUCVsldFxwRgVNDZI2eEi/view?usp=sharing
https://drive.google.com/file/d/1nWNJSJwlVlaJx4py1MpptH5ngZS4GMAn/view?usp=sharing
https://drive.google.com/file/d/1rDgPc5Pfw4N7FR3J46B3sjpfZQppz9IP/view?usp=sharing

**Comment by CreatiCoding** [comment]
bootstrap
http://bootstrapk.com/getting-started/

**Comment by CreatiCoding** [comment]
스터디 종료
