### ISSUE TITLE
cloud Function - data parsing

### ISSUE THREAD

**Issue by tentasys** [CreatiCoding/CoUPWA#30]
강희정 - cloud Function - 요일,웹툰명 api 요청 파라미터 : 요일 (0~6) 응답 값 : 해당 요일의 웹툰 이름들 ['마음의 소리','노블레스',,,]

**Comment by tentasys** [comment]
요일이 요청값으로 들어오면 해당 요일에 포함된 웹툰 데이터를 반환해 줍니다.

**Comment by tentasys** [comment]
웹툰 데이터 가져오는것까지 진행 - 요일별 웹툰명은 완료되지 않음

**Comment by tentasys** [comment]
@CreatiCoding cloud function 작업물은 CoUPWA/project/functions/ 에다가 커밋하면 되는건가요?

**Comment by CreatiCoding** [comment]
@tentasys 알람이 안왓었네연
Firebase Cloud Functions에 관해서 내일 회의때 말할거지만
여러개 js 파일을 동시에 등록할 거에요
내일 자세하게 말씀드리께여
