### ISSUE TITLE
네이버 웹툰 서비스 데이터 준비

### ISSUE THREAD

**Issue by tentasys** [CreatiCoding/CoUPWA#6]
네이버 웹툰 서비스의 데이터를 가져오는 방법에 대한 조사 및 관련 코드 작성

**Comment by tentasys** [comment]
웹툰 이미지 서버 : http://imgcomic.naver.net/webtoon
데이터 서버 접근 권한이 없기 때문에 접근 권한을 요청하거나 웹 페이지 크롤링을 이용해야 한다고 생각합니다.

아래는 네이버 웹툰 크롤러 예제입니다.
https://github.com/TurtleShip/webtoon-crawler
https://github.com/erishforG/lupin_crawler
https://github.com/suhjohn/Naver_Webtoon_Crawler

**Comment by tentasys** [comment]
webtoon crawler 실행 및 간단한 webtoon crawler 구현을 시도해 보려고 합니다.

**Comment by CreatiCoding** [comment]
좋은 생각 입니다. 현재 저희 프로젝트 방향이 static hosting을 이용하고 있기 때문에 crawler 코드를 돌릴 백엔드가 없습니다. 생각 좀 해본 결과, aws의 lambda와 같은 serverless 형태의 기능이 있다면 좋다고 생각했는데 마침 firebase에도 cloud functions 이라는 비슷한 기능을 제공해 주고 있었습니다. 오늘 회의 때 자세하게 말씀 드리겠습니다.

**Comment by tentasys** [comment]
@CreatiCoding 그럼 현재 가능한 범위에서의 issue는 마쳤다 생각하고 issue를 close하도록 하겠습니다. 추가 이슈는 다음 이슈로 작성하겠습니다.
