### ISSUE TITLE
리스트 페이지 참고 자료

### ISSUE THREAD

**Issue by CreatiCoding** [CreatiCoding/CoUPWA#66]
여기 사이트 분석해서
리스트 페이지에 사용될 부분을 이용

https://bootsnipp.com/snippets/dm9N

**Comment by CreatiCoding** [comment]
![image](https://user-images.githubusercontent.com/33514304/37004278-34692678-2113-11e8-9328-5a6e23d1965e.png)
이렇게 코드 볼수 있어요

**Comment by CreatiCoding** [comment]
@Rohheejung 이슈 확인했으면 "확인했습니다"라고 해주세ㅐ요

**Comment by Rohheejung** [comment]
확인했습니다!
