### ISSUE TITLE
리스트 페이지 파싱

### ISSUE THREAD

**Issue by CreatiCoding** [CreatiCoding/CoUPWA#70]
### [Nodejs 환경에서 개발 요망합니당]

Firebase Function으로의 변환은 아직 진행하지 말아주세요.
개발 테스트시 
```
cmd> node test.js
```
이런식으로 테스트해주세요.

### 파싱할 url : 
http://m.comic.naver.com/webtoon/list.nhn?titleId=[웹툰번호]&page=[페이지번호]

ex) http://m.comic.naver.com/webtoon/list.nhn?titleId=704595&page=1

###  파싱 내용 : 회차 배너 이미지 url, 회자 제목, 별점, 날짜 4가지 문자열 형태

ex) 
![image](https://user-images.githubusercontent.com/33514304/37147052-fe0180c4-2308-11e8-9f41-d4b947d4f743.png)

### 파싱 대상 : 페이지당 30개씩 있습니다. 30개 모두 파싱합니다.

나중에는 회차 개수를 파악하여 모든 페이지에 있는 회차를 파싱할 것입니당.

작업 진행하고 문제 생기면 SLACK으로 알려주세여.

GITHUB는 알람이 안오네여ㅠ

**Comment by tentasys** [comment]
확인했습니다 참고해서 진행하겠습니다~

**Comment by tentasys** [comment]
다음과 같이 웹툰 배너의 url, 웹툰명, 별점, 업데이트 순서를 가져오는데 성공하였습니다.
![image](https://user-images.githubusercontent.com/13197487/37389870-4a4e440e-27a9-11e8-80dd-bbeca80f2a10.png)

표시한 것과 같이 미리보기가 지원되는 웹툰의 경우 제목과 이미지 배너 링크를 가져올 수 있는 것으로 확인되었습니다.
아직 node.js로 구현한 것이고 firebase function으로 이식하지 않았기에 고려하지 않았지만 참고할 만한 사항인 것 같습니다.
+모바일 페이지와 pc 웹 페이지의 태그명이 달라서 pc를 기준으로 구현해도 똑같은 결과가 나오리라고는 할 수 없을 것 같습니다.

**Comment by tentasys** [comment]
![image](https://user-images.githubusercontent.com/13197487/37390405-4c953bf8-27ab-11e8-8f2e-e240cb65e205.png)
웹툰 title id와 페이지 번호를 인자로 준 경우입니다.

**Comment by tentasys** [comment]
미리보기의 경우 나중에 활용하는 방안으로 생각합니다.

**Comment by CreatiCoding** [comment]
넹
