### ISSUE TITLE
무손실 압축 구현

### ISSUE THREAD

**Issue by tentasys** [CreatiCoding/CoUPWA#72]
이미지를 로딩하는데 너무 많은 시간이 소요되어 이미지의 용량을 줄이는 방법을 고안합니다.
무손실 압축 외에도 이미지의 화질은 보존하면서 로딩 속도를 높일 수 있는 방법을 생각합니다.

**Comment by CreatiCoding** [comment]
jpg 자체가 무손실 압축 포맷이라 png -> jpg 변환만 작업하면 될거에여.

**Comment by CreatiCoding** [comment]
https://stackoverflow.com/questions/42218785/convert-base64-png-to-jpeg-image-in-nodejs

**Comment by CreatiCoding** [comment]
https://github.com/marekventur/png-to-jpeg

**Comment by CreatiCoding** [comment]
좋은 라이브러리를 찾았습니다.

[GraphicsMagick](https://github.com/aheckmann/gm)

**Comment by CreatiCoding** [comment]
사용 예입니다.
(예제)[https://stackoverflow.com/questions/16652054/converting-a-png-buffer-to-a-jpg-in-graphicsmagick-in-node#answer-27985409]
![image](https://user-images.githubusercontent.com/33514304/37615980-e3c2d14e-2bf1-11e8-8ef3-ae72ff9b8e89.png)

**Comment by CreatiCoding** [comment]
대신 gm의 경우 이런 식으로 작성해야합니다.
[출처](https://github.com/aheckmann/gm/issues/455#issuecomment-245049155)
![image](https://user-images.githubusercontent.com/33514304/37616534-9bd6889c-2bf3-11e8-8ab3-c2501935295c.png)

**Comment by CreatiCoding** [comment]
최종 사용법입니다.

```
const gm = require("gm").subClass({imageMagick: true});
const fs = require("fs");
gm("./test.png")
        .compress("JPEG")
        .write('./test.jpg', function(err){
                if(err)console.log(err);
        });
```
이 이미지는 오른쪽 png이미지(600,1600)을  jpg로 압축변환(600, 1600)하였을 때의 결과입니다.
608.6kb 에서 183.0kb로 용량이 줄었습니다.
2000% 확대 하였을때  육안으로 비교하여 별 다른 차이를 못 느꼈습니다.
실제로 픽셀 수도 같습니다.
![image](https://user-images.githubusercontent.com/33514304/37617852-a7fa8ff2-2bf7-11e8-81b9-2acc65879b2e.png)
이 이미지는 143%에서의 비교입니다.
![image](https://user-images.githubusercontent.com/33514304/37618033-22b916aa-2bf8-11e8-8d3e-9f2807a035db.png)
아래는 jpg 를 jpg로 압축만 진행한 결과입니다.
![image](https://user-images.githubusercontent.com/33514304/37618150-9b3af634-2bf8-11e8-9cc3-1dfd2c0187fd.png)
아래는 jpg 를 여러번 압축한 결과입니다.
이미 압축되어 있기에 용량이 변하지 않습니다. 육안으로 구별하기 힘듭니다.
![image](https://user-images.githubusercontent.com/33514304/37618233-f4be1c86-2bf8-11e8-933c-6b5e5fbb0c60.png)

**Comment by CreatiCoding** [comment]
png -> jpg나, jpg->jpg 의 경우 이미지에 따라 압축되는 정도가 다릅니다. 하지만 결론적으로 최대 압축에 도달한 경우 더이상 압축되지 않고 화질이 보장됩니다.
## 따라서 다운받은 이미지는 한 번정도 이 작업 거쳐 클라우드 스토리지에 저장하겠습니다.

**Comment by tentasys** [comment]
@CreatiCoding 압축 뿐만 아니라 리사이징을 고려하지 않아도 되는지 궁금합니다.
리사이징을 고려하면 이미지의 용량을 더 줄일 수 있을 것이라 생각합니다.
각각의 디바이스별 사이즈를 고려해서 리사이징을 하는 방향으로 구현하면 어떨까 생각중인데 어떻게 생각하시나요??

**Comment by CreatiCoding** [comment]
@tentasys 저번 중간보고때도 스마트폰 화면이 달라도 웹툰 앱에서 보던 것과 미세하게 다른점을 느낄 거라고 하셨죠. jpg로 선택한 이유는 손실이 없는 압축기법이였기 때문이에요. 리사이즈된다면 손실이 없을 없기에 조금 지양해야된다고 생각합니다.
그리구 지금 성능을 개선시키기 위해선 이미지 크기를 줄이는 것보단 프로그램 구조를 바꾸는게 맞다고 생각됩니당
